version: '3.9'
services:
  dev-tr-web-2023:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app:cached
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    ports:
      - '5173:5173'
    command: yarn dev --host

volumes:
  node_modules:
